[build] 
  base = "frontend" 
  publish = "dist" 
  command = "npm run build:prod"

[build.environment]
NODE_VERSION = "18"
NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
from = "/api/*"
to = "https://kpp2-production.up.railway.app/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
directory = "netlify/functions"